name: leaf_app
description: A new Flutter project. WIP for leaf project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.1.1 <4.0.0"  # Ensure the SDK is properly constrained for Dart 3

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add this section to define the assets for your project
  assets:
    - web/leaf_icons/leaf_logo.png
